name: stale

on:
    schedule:
        - cron: "31 22 * * *" # Runs every day at 10:31 PM UTC

    workflow_dispatch:

permissions: read-all

jobs:
    stale:
        uses: eslint/workflows/.github/workflows/stale.yml@main
        secrets:
            token: ${{ secrets.GITHUB_TOKEN }}
