name: update-readme

on:
    schedule:
        - cron: "0 8 * * *" # Runs every day at 08:00 AM UTC

    workflow_dispatch:

jobs:
    update-readme:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repo
              uses: actions/checkout@v4
            #  with:
            #      token: ${{ secrets.WORKFLOW_PUSH_BOT_TOKEN }}

            - name: Set up Node.js
              uses: actions/setup-node@v4

            - name: Update README with latest sponsor data
              run: |
                node --input-type=module -e "
                  //-----------------------------------------------------------------------------
                  // Import
                  //-----------------------------------------------------------------------------

                  import { readFileSync, writeFileSync } from "node:fs";

                  //-----------------------------------------------------------------------------
                  // Data
                  //-----------------------------------------------------------------------------

                  const SPONSORS_URL = "https://raw.githubusercontent.com/eslint/eslint.org/main/includes/sponsors.md";
                  const README_FILE_PATH = "./README.md";

                  //-----------------------------------------------------------------------------
                  // Main
                  //-----------------------------------------------------------------------------

                  const res = await fetch(SPONSORS_URL);
                  const allSponsors = await res.text();

                  console.log(allSponsors);
                "

            # - name: Setup Git
            #  run: |
            #      git config user.name "GitHub Actions Bot"
            #      git config user.email "<eslint@googlegroups.com>"

            # - name: Save updated files
            #   run: |
            #       chmod +x ./tools/commit-readme.sh
            #       ./tools/commit-readme.sh
